// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Ceqh21U_WJVj8n3CHxV_sNdF0HsQDgo',
    appId: '1:704905740833:web:594f654a26e30cf51b1960',
    messagingSenderId: '704905740833',
    projectId: 'splashup-app',
    authDomain: 'splashup-app.firebaseapp.com',
    storageBucket: 'splashup-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXunmcOSWv6rONhvkzgvZaLeffdkrSbjE',
    appId: '1:704905740833:android:ab93d893dce32df81b1960',
    messagingSenderId: '704905740833',
    projectId: 'splashup-app',
    storageBucket: 'splashup-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPtgqvB1YZP89PmLszI1w6oXtUpAsXwjU',
    appId: '1:704905740833:ios:470080f8e2d7d9691b1960',
    messagingSenderId: '704905740833',
    projectId: 'splashup-app',
    storageBucket: 'splashup-app.firebasestorage.app',
    iosBundleId: 'com.example.splashup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPtgqvB1YZP89PmLszI1w6oXtUpAsXwjU',
    appId: '1:704905740833:ios:470080f8e2d7d9691b1960',
    messagingSenderId: '704905740833',
    projectId: 'splashup-app',
    storageBucket: 'splashup-app.firebasestorage.app',
    iosBundleId: 'com.example.splashup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_Ceqh21U_WJVj8n3CHxV_sNdF0HsQDgo',
    appId: '1:704905740833:web:1ee4d50ac52035711b1960',
    messagingSenderId: '704905740833',
    projectId: 'splashup-app',
    authDomain: 'splashup-app.firebaseapp.com',
    storageBucket: 'splashup-app.firebasestorage.app',
  );
}
