import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../l10n/app_localizations.dart';
import '../repositories/database_repository.dart';
import '../models/athlete_model.dart';

class AddAthleteScreen extends StatefulWidget {
  // Update: Now we only need the ID of the father team
  final String teamId;

  const AddAthleteScreen({super.key, required this.teamId});

  @override
  State<AddAthleteScreen> createState() => _AddAthleteScreenState();
}

class _AddAthleteScreenState extends State<AddAthleteScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _notesController = TextEditingController();

  int? _selectedBirthYear;
  late List<int> _birthYearOptions;

  String _gender = 'Male';
  bool _isActive = true;
  final Map<String, bool> _preferredStyles = {
    'Freestyle': false,
    'Butterfly': false,
    'Backstroke': false,
    'Breaststroke': false,
    // 'IM' mancava anche qui: impossibile assegnarlo in fase di creazione
    'IM': false,
  };

  bool _isDirty = false;
  // Default per l'anno di nascita, serve anche al check "form modificato"
  late final int _defaultBirthYear;

  @override
  void initState() {
    super.initState();
    final currentYear = DateTime.now().year;
    _birthYearOptions = List.generate(100, (index) => currentYear - index);
    // Default sensato: prima era l'anno corrente (atleta di 0 anni),
    // errore facile da non notare in fase di inserimento.
    _defaultBirthYear = currentYear - 10;
    _selectedBirthYear = _defaultBirthYear;

    _nameController.addListener(() => _markDirty(true));
    _notesController.addListener(() => _markDirty(true));
  }

  void _markDirty(bool isDirty) {
    if (_isDirty != isDirty) {
      setState(() {
        _isDirty = isDirty;
      });
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<bool> _canPop() async {
    // Only show dialog if the form has been touched and is not empty.
    // Il check ora copre TUTTI i campi: prima genere, anno di nascita e
    // stato attivo erano ignorati e si potevano perdere senza warning.
    final formIsDirty = _nameController.text.isNotEmpty ||
        _notesController.text.isNotEmpty ||
        _preferredStyles.containsValue(true) ||
        _gender != 'Male' ||
        _selectedBirthYear != _defaultBirthYear ||
        !_isActive;

    if (!formIsDirty) return true;

    if (!mounted) return true;
    final currentContext = context;
    final l10n = AppLocalizations.of(currentContext)!;

    final shouldPop = await showDialog<bool>(
      context: currentContext,
      builder: (dialogContext) => AlertDialog(
        title: Text(l10n.unsavedChanges),
        content: Text(l10n.discardChangesWarning),
        actions: <Widget>[
          TextButton(
            onPressed: () => Navigator.of(dialogContext).pop(false),
            child: Text(l10n.cancel),
          ),
          TextButton(
            onPressed: () => Navigator.of(dialogContext).pop(true),
            child: Text(l10n.discard),
          ),
        ],
      ),
    );
    return shouldPop ?? false;
  }

  Future<void> _saveAthlete() async {
    // Capture l10n before any await so it is safe to use after async gaps.
    final l10n = AppLocalizations.of(context)!;
    if (_formKey.currentState!.validate()) {
      final selectedStyles = _preferredStyles.entries
          .where((entry) => entry.value)
          .map((entry) => entry.key)
          .toList();

      // New: Create the Object local Athlete
      final newAthlete = Athlete(
        id: '', // The ID will be automatically generated by the Repository
        name: _nameController.text.trim(),
        birthYear: _selectedBirthYear ?? 2000,
        gender: _gender,
        preferredStyles: selectedStyles,
        isActive: _isActive,
        notes: _notesController.text.trim(),
      );

      // NEW: Saving via Repository
      final db = context.read<DatabaseRepository>();
      final navigator = Navigator.of(context);
      final messenger = ScaffoldMessenger.of(context);

      // Prima salviamo, POI chiudiamo la schermata: col pop anticipato un
      // eventuale errore di scrittura veniva solo loggato e l'utente
      // credeva di aver salvato.
      try {
        await db.addAthlete(widget.teamId, newAthlete);
      } catch (e) {
        debugPrint('Error saving athlete: $e');
        if (mounted) {
          messenger.showSnackBar(
            SnackBar(content: Text(l10n.errorSavingAthlete(e.toString()))),
          );
        }
        return;
      }

      if (mounted) navigator.pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final Map<String, String> styleDisplayNames = {
      'Freestyle': l10n.freestyle,
      'Butterfly': l10n.butterfly,
      'Backstroke': l10n.backstroke,
      'Breaststroke': l10n.breaststroke,
      'IM': l10n.im,
    };

    return PopScope(
      canPop: false,
      onPopInvokedWithResult: (didPop, result) async {
        if (didPop) return;
        final navigator = Navigator.of(context);
        final shouldPop = await _canPop();
        if (shouldPop && mounted) {
          navigator.pop();
        }
      },
      child: Scaffold(
        appBar: AppBar(
          title: Text(l10n.addNewAthlete),
          actions: [
            IconButton(
              icon: const Icon(Icons.save),
              onPressed: _saveAthlete,
            ),
          ],
        ),
        body: Form(
          key: _formKey,
          child: ListView(
            padding: const EdgeInsets.all(16.0),
            children: [
              TextFormField(
                controller: _nameController,
                decoration: InputDecoration(labelText: l10n.athleteName),
                textCapitalization: TextCapitalization.words,
                validator: (value) =>
                    value!.isEmpty ? l10n.pleaseEnterName : null,
              ),
              DropdownButtonFormField<int>(
                initialValue: _selectedBirthYear,
                decoration: InputDecoration(labelText: l10n.birthYear),
                items: _birthYearOptions.map((year) {
                  return DropdownMenuItem(
                    value: year,
                    child: Text(year.toString()),
                  );
                }).toList(),
                onChanged: (value) {
                  setState(() {
                    _selectedBirthYear = value;
                    _markDirty(true);
                  });
                },
                validator: (value) =>
                    value == null ? l10n.pleaseSelectYear : null,
              ),
              DropdownButtonFormField<String>(
                initialValue: _gender,
                decoration: InputDecoration(labelText: l10n.gender),
                items: [
                  DropdownMenuItem(value: 'Male', child: Text(l10n.male)),
                  DropdownMenuItem(value: 'Female', child: Text(l10n.female)),
                ],
                onChanged: (value) => setState(() {
                  _gender = value!;
                  _markDirty(true);
                }),
              ),
              const SizedBox(height: 16),
              Text(l10n.preferredStyles,
                  style: Theme.of(context).textTheme.titleMedium),
              ..._preferredStyles.keys.map((styleKey) {
                return CheckboxListTile(
                  title: Text(styleDisplayNames[styleKey]!),
                  value: _preferredStyles[styleKey],
                  onChanged: (value) =>
                      setState(() {
                        _preferredStyles[styleKey] = value!;
                        _markDirty(true);
                      }),
                );
              }),
              SwitchListTile(
                title: Text(l10n.status),
                subtitle: Text(_isActive ? l10n.active : l10n.inactive),
                value: _isActive,
                onChanged: (value) => setState(() {
                  _isActive = value;
                  _markDirty(true);
                }),
              ),
              TextFormField(
                controller: _notesController,
                decoration: InputDecoration(labelText: l10n.notes),
                maxLines: 3,
                textCapitalization: TextCapitalization.sentences,
              ),
            ],
          ),
        ),
      ),
    );
  }
}